apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
  name: hello-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: hello-deployment
  type: ClusterIP