apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-deployment
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-deployment
  template:
    metadata:
      labels:
        app: hello-deployment
    spec:
      containers:
      - image: europe-west4-docker.pkg.dev/${PROJECT_ID}/images/hello-app
        name: hello-app
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3