apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: gke-backend-policy
spec:
  default:
    securityPolicy: security-policy-gke
  targetRef:
    group: ""
    kind: Service
    name: hello-service
